<div ng-repeat="(key, collection) in data.collections" ng-cloak>
  <div ng-if="collection.games.length > 0 || (key == 'regular' && data.collections.regular.games.length == 0)">
    
    <div class="box-header mb-5">
      <h2 class="text-capitalize m-0">
        <span>{{ collection.entry.name }}</span>
      </h2>
    </div>

    <div ng-repeat="game in collection.games" class="box" data-id="{{ game.g.id }}" data-entry="{{ game.g.enter_date | date: 'dd. MM yyyy' }}">
      <div class="box-body">
        <div class="row no-gutters align-items-center">
          <div class="col-10 col-xl-8 box-title">
            {{ game.g.title }}
          </div>
          <div class="d-none d-xl-block col-12 col-md-3">
            <div class="box-label" ng-if="game.g.type_register == 1 || game.g.type_sms == 1 || game.g.type_buy == 1 || game.g.type_internet == 1 || game.g.type_submission == 1">Gewinnspiel-Typ</div>
            <div class="lh-0 d-flex">
              <i ng-if="game.g.type_register == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Registrierung erforderlich" class="fi flaticon-user mr-2"></i>
              <i ng-if="game.g.type_sms == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="SMS/Anruf erforderlich" class="fi flaticon-tablet mr-2"></i>
              <i ng-if="game.g.type_buy == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Produktkauf erforderlich" class="loh mr-2"></i>
              <i ng-if="game.g.type_internet == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Online-Spiel" class="fi flaticon-gamepad mr-2"></i>
              <i ng-if="game.g.type_submission == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Kreativ-Einsendung erforderlich" class="fi flaticon-idea mr-2"></i>
            </div>
          </div>
          <div class="col-2 col-xl-1 text-right">              
            <div class="dropdown float-right">
              <a href class="btn btn-link text-secondary py-2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a href ng-click="toggleTagView(game.company.id, 'company')" class="dropdown-item">Anbieter ausblenden</a>
                <a href ng-if="checkCat(game)" ng-click="openModal(game)" class="dropdown-item" data-toggle="modal" data-target="#hideTagsModal">Kategorie ausblenden</a>
                <a href ng-click="reportGame(game)" class="dropdown-item" data-toggle="modal" data-target="#reportGameModal">Fehler melden</a>
              </div>
            </div>              
          </div>
        </div>
        <hr>
        <div class="row no-gutters">
          <div class="col-12 col-md-7">
            <p>
              <span class="box-label">Anbieter</span>
              <a ng-href="/{{ game.company.tag }}-gewinnspiele" class="text-body">{{ game.company.name }}</a>
            </p>
            <p ng-if="game.g.price">
              <span class="box-label"><span ng-if="game.g.price_info == 1">Info</span><span ng-if="game.g.price_info == 0">Preis</span></span>
              <span class="pre-wrap" ng-bind-html="game.g.price"></span>
            </p>
          </div>
          <div class="col-12 col-md-4 ml-auto">
            <p><span class="box-label">Einsendeschluss</span>{{ game.g.deadline_date | date: 'dd. MMMM yyyy' }}</p>
            <p ng-if="game.g.suggested_solution">
              <span class="box-label">Lösungsvorschlag</span>
              <span>{{ game.g.suggested_solution }}</span>
            </p>
          </div>
          <div class="col-12 d-block d-xl-none">
            <div class="box-label" ng-if="game.g.type_register == 1 || game.g.type_sms == 1 || game.g.type_buy == 1 || game.g.type_internet == 1 || game.g.type_submission == 1">Gewinnspiel-Typ</div>
            <div class="d-flex lh-0">
              <i ng-if="game.g.type_register == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Registrierung erforderlich" class="fi flaticon-user mr-2"></i>
              <i ng-if="game.g.type_sms == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="SMS/Anruf erforderlich" class="fi flaticon-tablet mr-2"></i>
              <i ng-if="game.g.type_buy == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Produktkauf erforderlich" class="loh mr-2"></i>
              <i ng-if="game.g.type_internet == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Online-Spiel" class="fi flaticon-gamepad mr-2"></i>
              <i ng-if="game.g.type_submission == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Kreativ-Einsendung erforderlich" class="fi flaticon-idea mr-2"></i>
            </div>
          </div>
        </div>
      </div>
      <div class="box-footer d-flex flex-column align-items-md-center flex-md-row">
        <div class="box-btn order-md-1 ml-md-auto flex-wrap flex-md-nowrap">
          <div class="w-50 w-md-auto pr-1 pr-md-0 mr-md-2" ng-if="!game.is_view && !game.hide_id">
            <a href ng-if="!game.save_id" ng-click="toFavCollection(game)" class="btn btn-theme btn-block box-save-btn">Merken</a>
          </div>              
          <div ng-if="!game.is_view" class="w-50 w-md-auto pl-1 pl-md-0 mr-md-2">
            <a href ng-click="toHideCollection(game, key)" class="btn btn-outline-mute btn-block box-hide-btn">Ausblenden</a>
          </div>
          <a ng-href="/win/{{ game.g.id }}" ng-click="toViewCollection(game)" target="_blank" rel="noopener noreferrer" class="btn w-100 w-md-auto btn-outline-warning">Zum Gewinnspiel</a>
        </div>
        <div ng-if="game.tags.length > 0" class="box-tags order-md-0">
          <a ng-repeat="tag in game.tags" ng-href="/{{ tag.tag }}-gewinnspiel" class="text-muted mr-2 mr-md-4 d-inline-block"><i class="fas fa-tags fa-flip-horizontal fa-xs mr-2"></i>{{ tag.name }}</a>
        </div>
      </div>
    </div>
    
    <div class="box" ng-if="key == 'regular' && data.collections.regular.games.length == 0">
      <div class="box-body text-center py-7">    
        <div class="row">
          <div class="col-12 col-md-9 col-lg-8 mx-auto" ng-if="data.all_count > 0">
            <p class="mb-7">Du hast Gewinnspiele ausgeblendet,<br class="d-none d-lg-block">dadurch werden nicht alle angezeigt.</p>
            <a href="/no-filter" class="btn btn-block btn-theme">Weitere Gewinnspiele anzeigen</a>
          </div>
          <div class="col-12 col-md-9 col-lg-8 mx-auto" ng-if="data.all_count ==0 ">
            <p class="mb-0">Keine Gewinnspiele mehr <br class="d-none d-lg-block">vorhanden - schaue morgen wieder vorbei</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



