<div ng-repeat="(key, collection) in data.collections" ng-cloak>
  <div class="box-header mb-5 d-flex align-items-center">
    <div>
      <h2 class="text-capitalize m-0">
        <span>{{ collection.entry.name }}</span>
      </h2>
      <p class="lead" ng-if="collection.entry.description">{{ collection.entry.description }}</p>
    </div>
    <div class="ml-auto pl-50px">
      <a href="/gewinnspiele" class="btn btn-outline-warning"><span class="px-2">&lsaquo;</span><span class="pr-2">Zurück zur Liste</span></a>
    </div>
  </div>

  <div class="alert alert-danger text-source d-flex align-items-center" ng-show="collection.entry.is_hide" role="alert">
    <div>
      <b>Hinweis:</b> Du hast diesen Anbieter bereits ausgeschlossen und siehst daher keine Gewinnspiele auf deiner persönlichen Startseite.
    </div>
    <a href class="btn btn-outline-warning ml-5" ng-click="toggleTagView(collection.entry.id, 'tag')">
      <span>Tag wieder einblenden</span>
    </a>
  </div>

  <div class="alert alert-success text-source" ng-show="showTagSuccess && !collection.entry.is_hide" role="alert">
    <b>Hinweis:</b> Anbieter wieder erfolgreich eingeblendet
  </div>

  <div ng-repeat="game in collection.games" class="box">
    <div class="box-body">
      <div class="row no-gutters align-items-center">
        <div class="col-10 col-xl-8 box-title">
          {{ game.g.title }}
        </div>
        <div class="d-none d-xl-block col-12 col-md-3">
          <div class="box-label" ng-if="game.g.type_register == 1 || game.g.type_sms == 1 || game.g.type_buy == 1 || game.g.type_internet == 1 || game.g.type_submission == 1">Gewinnspiel-Typ</div>
          <div class="lh-0 d-flex">
            <i ng-if="game.g.type_register == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Registrierung erforderlich" class="fi flaticon-user mr-2"></i>
            <i ng-if="game.g.type_sms == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="SMS/Anruf erforderlich" class="fi flaticon-tablet mr-2"></i>
            <i ng-if="game.g.type_buy == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Produktkauf erforderlich" class="loh mr-2"></i>
            <i ng-if="game.g.type_internet == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Online-Spiel" class="fi flaticon-gamepad mr-2"></i>
            <i ng-if="game.g.type_submission == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Kreativ-Einsendung erforderlich" class="fi flaticon-idea mr-2"></i>
          </div>
        </div>
        <div class="col-2 col-xl-1 text-right">              
          <div class="dropdown float-right">
            <a href class="btn btn-link text-secondary py-2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              <a href ng-click="toggleTagView(game.company.id, 'company')" class="dropdown-item">Anbieter ausblenden</button>
              <a href ng-if="game.tags.length > 1"  ng-click="openModal(game)" class="dropdown-item" data-toggle="modal" data-target="#hideTagsModal">Tags/Preise ausschließen</a>           
              <a href ng-if="!collection.entry.is_hide && game.tags.length == 1" ng-click="toggleTagView(collection.entry.id, 'tag')" class="dropdown-item">Tags/Preise ausschließen</button>
              <a href ng-click="reportGame(game)" class="dropdown-item" data-toggle="modal" data-target="#reportGameModal">Gewinnspiel melden</a>
            </div>
          </div>              
        </div>
      </div>
      <hr>
      <div class="row no-gutters">
        <div class="col-12 col-md-7">
          <p>
            <span class="box-label">Anbieter</span>
            <a ng-href="/{{ game.company.tag }}-gewinnspiele" class="text-body">{{ game.company.name }}</a>
          </p>
          <p ng-if="game.g.price">
            <span class="box-label"><span ng-if="game.g.price_info">Info</span><span ng-if="!game.g.price_info">Preis</span></span>
            <span ng-bind-html="game.g.price"></span>
          </p>
        </div>
        <div class="col-12 col-md-4 ml-auto">
          <p><span class="box-label">Einsendeschluss</span>{{ game.g.deadline_date | date: 'dd. MMMM yyyy' }}</p>
          <p ng-if="game.g.suggested_solution">
            <span class="box-label">Lösungsvorschlag</span>
            <span>{{ game.g.suggested_solution }}</span>
          </p>
        </div>
        <div class="col-12 d-block d-xl-none">
          <div class="box-label" ng-if="game.g.type_register == 1 || game.g.type_sms == 1 || game.g.type_buy == 1 || game.g.type_internet == 1 || game.g.type_submission == 1">Gewinnspiel-Typ</div>
          <div class="d-flex lh-0">
            <i ng-if="game.g.type_register == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Registrierung erforderlich" class="fi flaticon-user mr-2"></i>
            <i ng-if="game.g.type_sms == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="SMS/Anruf erforderlich" class="fi flaticon-tablet mr-2"></i>
            <i ng-if="game.g.type_buy == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Produktkauf erforderlich" class="loh mr-2"></i>
            <i ng-if="game.g.type_internet == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Online-Spiel" class="fi flaticon-gamepad mr-2"></i>
            <i ng-if="game.g.type_submission == 1" tooltip data-toggle="tooltip" data-placement="bottom" title="Kreativ-Einsendung erforderlich" class="fi flaticon-idea mr-2"></i>
          </div>
        </div>
      </div>
    </div>
    <div class="box-footer d-flex flex-column align-items-md-center flex-md-row">
      <div class="box-btn order-md-1 ml-md-auto flex-wrap flex-md-nowrap">
        <div class="w-50 w-md-auto pr-1 pr-md-0 mr-md-2">
          <a href ng-if="!game.save_id" ng-click="toFavCollection(game)" class="btn btn-theme btn-block box-save-btn">Merken</a>
        </div>              
        <div ng-if="!game.is_view" class="w-50 w-md-auto pl-1 pl-md-0 mr-md-2">
          <a href ng-click="toHideCollection(game, key)" class="btn btn-outline-mute btn-block box-hide-btn">Ausblenden</a>
        </div>
        <a ng-href="/win/{{ game.g.id }}" ng-click="toViewCollection(game)" target="_blank" rel="noopener noreferrer" class="btn w-100 w-md-auto btn-outline-warning">Zum Gewinnspiel</a>
      </div>
      <div ng-if="game.tags.length > 0" class="box-tags order-md-0">
        <a ng-repeat="tag in game.tags" ng-href="/{{ tag.tag }}-gewinnspiel" class="text-muted mr-2 mr-md-4 d-inline-block"><i class="fas fa-tags fa-flip-horizontal fa-xs mr-2"></i>{{ tag.name }}</a>
      </div>
    </div>
  </div>

  <div class="box" ng-if="data.collections.regular.games.length == 0">
    <div class="box-body text-center py-7">    
      <div class="row">
        <div class="col-12 col-md-9 col-lg-8 mx-auto">
          <div class="box-label mb-5">Filter aktiv</div>
          <p class="mb-7">Du nutzt einen Filter, dadurch werden nicht alle <br class="d-none d-lg-block">Gewinnspiele angezeigt.</p>
          <a href="/no-filter" class="btn btn-block btn-theme">Weitere Gewinnspiele anzeigen</a>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="hideTagsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body p-4 p-md-7">
        <h3 class="text-theme">Tags/Preise ausschließen</h3>
        <p class="lead">Welche Tags wollen Sie ausschließen</p>
        <div class="mb-5" id="modal_tags_list">
          <div class="custom-control custom-checkbox" ng-repeat="tag in modalTags">
            <input type="checkbox" class="custom-control-input" name="tags_id[]" checklist-model="tags_id" checklist-value="tag.id" id="customCheck{{ tag.id }}">
            <label class="custom-control-label" for="customCheck{{ tag.id }}">{{ tag.name }}</label>
          </div>
        </div> 
        <button type="button" class="btn btn-secondary mr-3 mb-3" data-dismiss="modal">Abbruch</button>
        <button type="submit" ng-click="sendModal()" data-dismiss="modal" class="btn btn-theme mb-3">Jetzt ausschließen</button>     
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="reportGameModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body p-4 p-md-7">
        <h3 class="text-theme">Gewinnspiel melden</h3>
        <p class="lead">Etwas stimmt mit diesem Spiel nicht, dann teilen Sie uns mit was.</p>
        <form action="games/report" method="post" accept-charset="utf-8">
          <input type="hidden" name="games_id" id="reportGameId" value="{{ reportGameId }}" />
          <div class="form-group">
            <label for="report">Ihre Nachricht</label>
            <textarea id="report" name="report" class="form-control" placeholder="Nachricht" rows="4" required="required"></textarea>
          </div>         
          <button type="button" class="btn btn-secondary mr-3 mb-3" data-dismiss="modal">Abbruch</button>
          <button type="submit" class="btn btn-theme mb-3">Jetzt absenden</button>
        </form>        
      </div>
    </div>
  </div>
</div>