<!doctype html>
<html lang="de">
  <head>
    <base href="/">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/solid.min.css">
    <link rel="stylesheet" href="css/notify.css">
    <link rel="stylesheet" href="css/style.css">
    <!-- FontAwesome -->
    <?php echo $this->tag->getTitle(); ?>
    <?php if (isset($description)) : ?>
      <meta name="description" content="<?= $description; ?>">
    <?php endif; ?>

    <link rel="apple-touch-icon" sizes="57x57" href="<?= $this->url->get('apple-icon-57x57.png'); ?>">
    <link rel="apple-touch-icon" sizes="60x60" href="<?= $this->url->get('apple-icon-60x60.png'); ?>">
    <link rel="apple-touch-icon" sizes="72x72" href="<?= $this->url->get('apple-icon-72x72.png'); ?>">
    <link rel="apple-touch-icon" sizes="76x76" href="<?= $this->url->get('apple-icon-76x76.png'); ?>">
    <link rel="apple-touch-icon" sizes="114x114" href="<?= $this->url->get('apple-icon-114x114.png'); ?>">
    <link rel="apple-touch-icon" sizes="120x120" href="<?= $this->url->get('apple-icon-120x120.png'); ?>">
    <link rel="apple-touch-icon" sizes="144x144" href="<?= $this->url->get('apple-icon-144x144.png'); ?>">
    <link rel="apple-touch-icon" sizes="152x152" href="<?= $this->url->get('apple-icon-152x152.png'); ?>">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= $this->url->get('apple-icon-180x180.png'); ?>">
    <link rel="icon" type="image/png" sizes="192x192"  href="<?= $this->url->get('android-icon-192x192.png'); ?>">
    <link rel="icon" type="image/png" sizes="32x32" href="<?= $this->url->get('favicon-32x32.png'); ?>">
    <link rel="icon" type="image/png" sizes="96x96" href="<?= $this->url->get('favicon-96x96.png'); ?>">
    <link rel="icon" type="image/png" sizes="16x16" href="<?= $this->url->get('favicon-16x16.png'); ?>">
    <link rel="manifest" href="<?= $this->url->get('manifest.json'); ?>">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<?= $this->url->get('ms-icon-144x144.png'); ?>">
    <meta name="theme-color" content="#ffffff">
    <?= isset($google) ? $google : ''; ?>
  </head>
  <?php
    $controllerName = $this->router->getControllerName();
    $bodyClass = ((!$controllerName || in_array($controllerName, array('session'))) && !is_array($this->auth->getIdentity())) ? 'bg' : '';
  ?>
  <body class="d-flex justify-content-end flex-column <?php echo $bodyClass; ?>">
    
    <?php
      $messages = $this->flashSession->getMessages();
      if ($messages) { ?>
        <div class="toast-wrap">
        <?php foreach ($messages as $type => $data) {
          foreach ($data as $message) {
            ?>
            <div class="toast toast-danger" role="alert" aria-live="assertive" aria-atomic="true">
              <div class="d-flex position-relative">
                <span class="notify-close" data-dismiss="toast" aria-label="Close" aria-hidden="true">&times;</span>
                <div class="notify-icon">
                  <i class="fas fa-exclamation-circle"></i>
                </div>
                <div class="notify-body d-flex align-items-center">
                  <p class="m-0"><?= $message; ?></p>
                </div>
              </div>
            </div>
            <?php           
          }
        } ?>
      </div>
      <?php
      }

    ?>
    
    <header id="header" class="fixed-top">
      <nav class="navbar navbar-expand-lg navbar-light bg-white pt-lg-6">
        <div class="container">
          <a class="navbar-brand d-flex align-items-start" href="/">
            <img src="img/raffledo@1x.png" srcset="img/raffledo@1x.png 1x, img/raffledo.png 2x" alt="Raffledo">
            <img src="img/germany.png" srcset="img/germany.png 1x, img/germany@2x.png 2x" alt="Germany" class="ml-2">
          </a>
          <button class="ml-auto navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-body" aria-controls="navbar-body" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>          
          <div class="collapse navbar-collapse" id="navbar-body">             
            <?php if (is_array($this->auth->getIdentity())) : ?>
              <div class="d-flex align-items-center flex-wrap mt-5 mt-lg-0 ml-lg-auto">
                <form class="form w-100 w-md-auto mb-4 mb-md-0" method="post" action="/suche">
                  <div class="position-relative">
                    <input class="form-control mr-lg-6" type="search" name="search" placeholder="Suche" aria-label="Suche">
                    <button type="submit" class="btn-search btn btn-link"><i class="fas fa-search text-theme"></i></button>
                  </div>
                </form>
                <ul class="navbar-nav mr-7 ml-auto ml-lg-7">
                  <li class="nav-item active">
                    <?= $this->tag->linkTo(['einstellungen', 'Einstellungen', 'class' => 'nav-link']); ?>
                  </li>
                </ul>
                <?= $this->tag->linkTo(['logout', 'Logout', 'class' => 'btn px-5 btn-outline-theme']); ?>
              </div>              
            <?php else : ?>
              <div class="ml-auto mt-5 mt-lg-0">
                <?php if ($controllerName == 'games') : ?>
                  <?= $this->tag->linkTo(['#register', 'Registrierung', 'class' => 'btn px-5 btn-outline-theme mr-lg-4', 'data-scroll' => 'true']); //$this->router->getRewriteUri() . ?>
                <?php else : ?>
                  <?= $this->tag->linkTo(['#register', 'Registrierung', 'class' => 'btn px-5 btn-outline-theme mr-lg-4', 'data-scroll' => 'true']); ?>
                <?php endif; ?>                
                <?= $this->tag->linkTo(['login', 'Login', 'class' => 'btn px-5 btn-outline-theme']); ?>
              </div>
            <?php endif; ?>
          </div>
        </div>
      </nav>
      <div id="notify" class="position-relative"></div>
    </header><!-- /header -->
   
    <?php if ($controllerName != 'games') : ?>
      <main class="py-50px">
        <div class="container">         
    <?php endif; ?>

    <?= $this->getContent(); ?>
    <?php if ($controllerName != 'games') : ?>
        </div>
      </main>
    <?php endif; ?>

    <?php 
      $companies_footer = $this->modelsManager->createBuilder()
        ->from(['companies' => 'Raffledo\Models\Companies'])
        ->leftJoin('Raffledo\Models\Games', 'games.companies_id = companies.id', 'games')
        ->where('companies.footer = 1 AND games.enter_date <= CURDATE() AND games.deadline_date >= CURDATE()')
        ->having('count(games.id) > 0')
        ->groupBy('companies.id')
        ->limit(8)
        ->getQuery()->execute();

      $tags_footer= $this->modelsManager->createBuilder()
        ->from(['tags' => 'Raffledo\Models\Tags'])
        ->leftJoin('Raffledo\Models\GamesTags', 'gt.tags_id = tags.id', 'gt')
        ->leftJoin('Raffledo\Models\Games', 'games.id = gt.games_id', 'games')
        ->where('tags.footer = 1 AND games.enter_date <= CURDATE() AND games.deadline_date >= CURDATE()')
        ->having('count(gt.id) > 2')
        ->groupBy('tags.id')
        ->limit(4)
        ->getQuery()->execute();

      $user = $this->auth->getUser();
    ?>

    <footer class="bg-warning text-white py-7 footer-nav mt-auto">      
      <div class="container">
        <?php if ($controllerName) : ?>
        <div class="row mb-7">
          <div class="col-12 col-md-3">
            <h5 class="mb-4">Top Preise</h5>
            <ul class="list-unstyled">
              <?php foreach ($tags_footer as $tag) : ?>   
                <li><a href="/<?php echo $tag->tag; ?>-gewinnspiel" class="text-capitalize"><?php echo $tag->name; ?></a></li>
              <?php endforeach; ?>
            </ul>
          </div>
          <div class="col-12 col-md-6 col-lg-6">
            <h5 class="mb-4">Gewinnspiel Anbieter</h5>
            <div class="row">
              <div class="col">                
                <ul class="list-unstyled">
                  <?php foreach ($companies_footer as $key => $company) : if ($key < 4) : ?>   
                    <li><a href="/<?php echo $company->tag; ?>-gewinnspiele" class="text-capitalize"><?php echo $company->name; ?></a></li>
                  <?php endif; endforeach; ?>
                </ul>
              </div>
              <div class="col">                    
                <ul class="list-unstyled">
                  <?php foreach ($companies_footer as $key => $company) : if ($key > 3) : ?>   
                    <li><a href="/<?php echo $company->tag; ?>-gewinnspiele" class="text-capitalize"><?php echo $company->name; ?></a></li>
                  <?php endif; endforeach; ?>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-3">
            <h5 class="mb-4">Über Raffledo</h5>       
            <ul class="list-unstyled">
              <li><?= $this->tag->linkTo('impressum', 'Impressum'); ?></li>
              <li><?= $this->tag->linkTo('datenschutz', 'Datenschutz'); ?></li>
              <?php if ($user) : ?>
                <li><?= $this->tag->linkTo('neues', 'Neues Gewinnspiel melden'); ?></li>
                <li><?= $this->tag->linkTo('einstellungen', 'Einstellungen'); ?></li> 
              <?php endif; ?>
            </ul>
          </div>
        </div>
        <?php endif; ?>
        <div class="text-center">
          Copyright 2019 &bull; BAWS Websolutions GmbH &bull; Alle Reechte vorbehalten <?php if (!$controllerName) : ?>&bull; <?= $this->tag->linkTo('impressum', 'Impressum'); ?> &bull; <?= $this->tag->linkTo('datenschutz', 'Datenschutz'); ?><?php endif; ?>
        </div>
      </div>
    </footer>

    <script src="js/lib/jquery.min.js"></script>
    <script src="js/lib/popper.min.js"></script>
    <script src="js/lib/bootstrap.min.js"></script>
    <script src="js/jquery.smooth-scroll.min.js" type="text/javascript"></script>
    <?php if ($controllerName == 'games' && $user) : ?>
      <script src="js/angular/angular.min.js"></script>
      <script src="js/angular/angular-animate.min.js"></script>
      <script src="js/angular/angular-sanitize.min.js"></script>
      <script src="js/angular/angular-resource.min.js"></script>
      <script src="js/angular/angular-route.min.js"></script>
      <script src="js/angular/angular-locale_de-de.js"></script>      
      <script src="js/angular-checklist.js"></script>       
      <script src="js/angular-notify-2.min.js"></script>  
      <script src="js/app-min.js"></script>  
    <?php endif; ?>
    <script src="js/core-min.js"></script>
  </body>
</html>