<!doctype html>
<html lang="de">
  <head>
    <base href="/">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Muli:400,600,900|Source+Sans+Pro:400,600" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/style.css">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <title>Raffledo</title>

    <link rel="apple-touch-icon" sizes="57x57" href="<?= $this->url->get('apple-icon-57x57.png'); ?>">
    <link rel="apple-touch-icon" sizes="60x60" href="<?= $this->url->get('apple-icon-60x60.png'); ?>">
    <link rel="apple-touch-icon" sizes="72x72" href="<?= $this->url->get('apple-icon-72x72.png'); ?>">
    <link rel="apple-touch-icon" sizes="76x76" href="<?= $this->url->get('apple-icon-76x76.png'); ?>">
    <link rel="apple-touch-icon" sizes="114x114" href="<?= $this->url->get('apple-icon-114x114.png'); ?>">
    <link rel="apple-touch-icon" sizes="120x120" href="<?= $this->url->get('apple-icon-120x120.png'); ?>">
    <link rel="apple-touch-icon" sizes="144x144" href="<?= $this->url->get('apple-icon-144x144.png'); ?>">
    <link rel="apple-touch-icon" sizes="152x152" href="<?= $this->url->get('apple-icon-152x152.png'); ?>">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= $this->url->get('apple-icon-180x180.png'); ?>">
    <link rel="icon" type="image/png" sizes="192x192"  href="<?= $this->url->get('android-icon-192x192.png'); ?>">
    <link rel="icon" type="image/png" sizes="32x32" href="<?= $this->url->get('favicon-32x32.png'); ?>">
    <link rel="icon" type="image/png" sizes="96x96" href="<?= $this->url->get('favicon-96x96.png'); ?>">
    <link rel="icon" type="image/png" sizes="16x16" href="<?= $this->url->get('favicon-16x16.png'); ?>">
    <link rel="manifest" href="<?= $this->url->get('manifest.json'); ?>">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<?= $this->url->get('ms-icon-144x144.png'); ?>">
    <meta name="theme-color" content="#ffffff">

  </head>
  <?php
    $controllerName = $this->router->getControllerName();
    $bodyClass = ((!$controllerName || in_array($controllerName, array('session'))) && !is_array($this->auth->getIdentity())) ? 'bg' : '';
  ?>
  <body class="d-flex justify-content-end flex-column <?php echo $bodyClass; ?>">
    <div id="top"></div>
    <header id="header" class="fixed-top">
      <nav class="navbar navbar-expand-lg navbar-light bg-white pt-lg-6">
        <div class="container">
          <a class="navbar-brand d-flex align-items-start" href="/">
            <img src="img/raffledo@1x.png" srcset="img/raffledo@1x.png 1x, img/raffledo.png 2x" alt="Raffledo">
            <img src="img/germany.png" srcset="img/germany.png 1x, img/germany@2x.png 2x" alt="Germany" class="ml-2">
          </a>
          <button class="ml-auto navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-body" aria-controls="navbar-body" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>          
          <div class="collapse navbar-collapse" id="navbar-body">             
            <?php if (is_array($this->auth->getIdentity())) : ?>
              <ul class="navbar-nav ml-auto mr-7 mt-5 mt-lg-0">
                <li class="nav-item active">
                  <?= $this->tag->linkTo(['einstellungen', 'Einstellungen', 'class' => 'nav-link']); ?>
                </li>
              </ul>
              <?= $this->tag->linkTo(['logout', 'Logout', 'class' => 'btn px-5 btn-outline-theme mr-lg-4']); ?>
            <?php else : ?>
              <div class="ml-auto mt-5 mt-lg-0">
                <?php if ($controllerName == 'games') : ?>
                  <?= $this->tag->linkTo(['#register', 'Registrierung', 'class' => 'btn px-5 btn-outline-theme mr-lg-4', 'data-scroll' => 'true']); //$this->router->getRewriteUri() . ?>
                <?php else : ?>
                  <?= $this->tag->linkTo(['#register', 'Registrierung', 'class' => 'btn px-5 btn-outline-theme mr-lg-4', 'data-scroll' => 'true']); ?>
                <?php endif; ?>                
                <?= $this->tag->linkTo(['login', 'Login', 'class' => 'btn px-5 btn-outline-theme']); ?>
              </div>
            <?php endif; ?>
          </div>
        </div>
      </nav>
    </header><!-- /header -->
   
    <?php if ($controllerName != 'games') : ?>
      <main class="py-50px">
        <div class="container">
    <?php endif; ?>
    <?= $this->getContent(); ?>
    <?php if ($controllerName != 'games') : ?>
        </div>
      </main>
    <?php endif; ?>

    <?php 
      $companies_footer = $this->modelsManager->createBuilder()
        ->from(['companies' => 'Raffledo\Models\Companies'])
        ->leftJoin('Raffledo\Models\Games', 'games.companies_id = companies.id', 'games')
        ->leftJoin('Raffledo\Models\SavedGames', 'saved.games_id = games.id', 'saved')
        ->leftJoin('Raffledo\Models\HiddenGames', 'hidden.games_id = games.id', 'hidden')
        ->leftJoin('Raffledo\Models\HiddenCompanies', 'hc.companies_id = games.companies_id', 'hc')

        ->where('companies.footer = 1 AND saved.id IS NULL AND hidden.id IS NULL AND hc.id IS NULL')
        ->having('count(games.id) > 0')
        ->groupBy('companies.id')
        ->limit(8)
        ->getQuery()->execute();

      $tags_footer= $this->modelsManager->createBuilder()
        ->from(['tags' => 'Raffledo\Models\Tags'])
        ->where('tags.footer = 1')
        ->limit(4)
        ->getQuery()->execute();

      $user = $this->auth->getUser();
    ?>

    <div class="position-relative mt-auto">
      <a href="<?= $this->router->getRewriteUri(); ?>#top" class="btn btn-outline-theme btn-sm btn-top" data-scroll="true">Nach oben</a>
    </div>

    <footer class="bg-warning text-white py-7 footer-nav">      
      <div class="container">
        <?php if ($controllerName && $user) : ?>
        <div class="row mb-7">
          <div class="col-12 col-md-3">
            <h5 class="mb-4">Top Preise</h5>
            <ul class="list-unstyled">
              <?php foreach ($tags_footer as $tag) : ?>   
                <li><a href="/<?php echo $tag->tag; ?>-gewinnspiel" class="text-capitalize"><?php echo $tag->name; ?></a></li>
              <?php endforeach; ?>
            </ul>
          </div>
          <div class="col-12 col-md-6 col-lg-6">
            <h5 class="mb-4">Gewinnspiel Anbieter</h5>
            <div class="row">
              <div class="col">                
                <ul class="list-unstyled">
                  <?php foreach ($companies_footer as $key => $company) : if ($key < 4) : ?>   
                    <li><a href="/<?php echo $company->tag; ?>-gewinnspiele" class="text-capitalize"><?php echo $company->name; ?></a></li>
                  <?php endif; endforeach; ?>
                </ul>
              </div>
              <div class="col">                    
                <ul class="list-unstyled">
                  <?php foreach ($companies_footer as $key => $company) : if ($key > 3) : ?>   
                    <li><a href="/<?php echo $company->tag; ?>-gewinnspiele" class="text-capitalize"><?php echo $company->name; ?></a></li>
                  <?php endif; endforeach; ?>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-3">
            <h5 class="mb-4">Über Raffledo</h5>       
            <ul class="list-unstyled">
              <li><?= $this->tag->linkTo('impressum', 'Impressum'); ?></li>
              <li><?= $this->tag->linkTo('datenschutz', 'Datenschutz'); ?></li>
              <li><?= $this->tag->linkTo('neues', 'Neues Gewinnspiel melden'); ?></li>
              <li><?= $this->tag->linkTo('einstellungen', 'Einstellungen'); ?></li> 
            </ul>
          </div>
        </div>
        <?php endif; ?>
        <div class="text-center">
          Copyright 2019 &bull; BAWS Websolutions GmbH &bull; Alle Reechte vorbehalten <?php if (!$controllerName || !$user) : ?>&bull; <?= $this->tag->linkTo('impressum', 'Impressum'); ?> &bull; <?= $this->tag->linkTo('datenschutz', 'Datenschutz'); ?><?php endif; ?>
        </div>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="js/jquery.smooth-scroll.min.js" type="text/javascript"></script>
    <?php if ($controllerName == 'games' && $user) : ?>
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js"></script>
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-animate.min.js"></script>
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-sanitize.min.js"></script>
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-resource.min.js"></script>
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-route.min.js"></script>
      <script src="js/angular-checklist.js"></script>  
      <script src="js/app-min.js"></script>  
    <?php endif; ?>
    <script src="js/core-min.js"></script>
  </body>
</html>