<!doctype html>
<html lang="de">
  <head>
    <base href="/">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Muli:400,600,900|Source+Sans+Pro:400,600" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/style.css">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <title>Raffledo</title>
  </head>
  <?php
    $controllerName = $this->router->getControllerName();
    $bodyClass = ((!$controllerName || in_array($controllerName, array('session'))) && !is_array($this->auth->getIdentity())) ? 'bg' : '';
  ?>
  <body class="d-flex justify-content-end flex-column <?php echo $bodyClass; ?>">
    <header id="header" class="fixed-top">
      <nav class="navbar navbar-expand-lg navbar-light bg-white pt-lg-6">
        <div class="container align-items-lg-end">
          <a class="navbar-brand" href="/">
            <img src="img/raffledo.png" srcset="img/raffledo.png 1x, img/raffledo@2x.png 2x" alt="Raffledo">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-body" aria-controls="navbar-body" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
    
          <div class="collapse navbar-collapse" id="navbar-body">
            <?php if (is_array($this->auth->getIdentity())) : ?>
              <ul class="navbar-nav ml-auto mr-65px">
                <li class="nav-item">
                  <a class="nav-link" href="/favoriten">
                    Favoriten
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/neues">
                    Neues Gewinnspiel melden
                  </a>
                </li>
              </ul>
              <a href="/logout" class="btn px-5 btn-outline-theme mr-lg-4">Logout</a>
            <?php else : ?>
              <div class="ml-auto">
                <a href="/login" class="btn px-5 btn-outline-theme mr-lg-4">Login</a>
                <a href="/" class="btn px-5 btn-outline-theme">Registrierung</a>
              </div>
            <?php endif; ?>
            <div class="ml-4">
              <img src="img/germany.png" srcset="img/germany.png 1x, img/germany@2x.png 2x" alt="Germany">
            </div>
          </div>
        </div>
      </nav>
    </header><!-- /header -->

    <main class="py-65px">
      <div class="container">
        <?php
          echo $this->flashSession->output();
          echo $this->getContent(); 
        ?>
      </div>
    </main>


    <footer class="mt-auto">
      <div class="container">
        <div class="border-top border-theme"></div>
        <div class="d-flex py-6">
          <a href="http://fetz.cc/" target="_blank" class="d-block mx-auto">
            <img src="img/fetz.png" srcset="img/fetz.png 1x, img/fetz@2x.png 2x" alt="Othmar Fetz">
          </a>
        </div>
      </div>
    </footer>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="js/core-min.js"></script>
  </body>
</html>