<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Raffledo</title>
    <link rel="stylesheet" href="/css/style.css">
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    <link rel="stylesheet" href="/css/flaticon.css">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/bootstrap-tagsinput.css">
  </head>
  <body>

    <?php echo $this->getContent(); ?>

      
    <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->    
    <script src="/js/lib/jquery.min.js"></script>
    <script src="/js/lib/popper.min.js"></script>
    <script src="/js/lib/bootstrap.min.js"></script>
    
    <script type="text/javascript" src="/js/typeahead.bundle.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap-tagsinput.min.js"></script>
    <script type="text/javascript" src="/js/admin-min.js?w=<?php echo time(); ?>"></script>

  </body>
</html>




